### ISSUE TITLE
Exception: starting signal not seen within 11 seconds

### ISSUE THREAD

**Issue by g1patnaik** [bengland2/smallfile#5]
Hi, 

I don't understand why I get the below error.

```
[root@host1 smallfile]# python smallfile_cli.py --top /mnt/gluster/gv0_ganesha_nfs/smallfile --host-set host1,host2,host3,host4,host6,host7 --threads 8 --file-size 4 --files 10 --response-times Y --operation create
                                 version : 3.1
                           hosts in test : ['host1', 'host2', 'host3', 'host4', 'host6', 'host7']
                   top test directory(s) : ['/mnt/gluster/gv0_ganesha_nfs/smallfile']
                               operation : create
                            files/thread : 10
                                 threads : 8
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 4
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix :
                         filename suffix :
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : Y
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /root/smallfile
               network thread sync. dir. : /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared
starting all threads by creating starting gate file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/starting_gate.tmp
Traceback (most recent call last):
  File "/root/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/root/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/root/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 11 seconds
Traceback (most recent call last):
  File "/root/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/root/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/root/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 11 seconds
ERROR: ssh thread for host host2 completed with status 256
Traceback (most recent call last):
  File "/root/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/root/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/root/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 11 seconds
ERROR: ssh thread for host host3 completed with status 256
Traceback (most recent call last):
  File "/root/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/root/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/root/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 11 seconds
ERROR: ssh thread for host host4 completed with status 256
Traceback (most recent call last):
  File "/root/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/root/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/root/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 11 seconds
ERROR: ssh thread for host host6 completed with status 256
ERROR: ssh thread for host host7 completed with status 256
  pickle file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/host2_result.pickle not found
  pickle file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/host3_result.pickle not found
  pickle file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/host4_result.pickle not found
  pickle file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/host6_result.pickle not found
  pickle file /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared/host7_result.pickle not found
host = host1,thr = 00,elapsed = 1.292002,files = 10,records = 10,status = ok
host = host1,thr = 01,elapsed = 1.314542,files = 10,records = 10,status = ok
host = host1,thr = 02,elapsed = 1.298001,files = 10,records = 10,status = ok
host = host1,thr = 03,elapsed = 1.308788,files = 10,records = 10,status = ok
host = host1,thr = 04,elapsed = 1.302692,files = 10,records = 10,status = ok
host = host1,thr = 05,elapsed = 1.300747,files = 10,records = 10,status = ok
host = host1,thr = 06,elapsed = 1.293828,files = 10,records = 10,status = ok
host = host1,thr = 07,elapsed = 1.299923,files = 10,records = 10,status = ok
total threads = 8
total files = 80
total IOPS = 80
total data =     0.000 GiB
WARNING: failed to get some responses from workload generators
100.00% of requested files processed, minimum is  90.00
elapsed time =     1.315
files/sec = 60.857695
IOPS = 60.857695
MiB/sec = 0.237725
```

And FYI, I have edited the ssh_thread.py script as follows for passwordless authentication:

`ssh_prefix = 'ssh -i /var/lib/glusterd/nfs/secret.pem -x -o StrictHostKeyChecking=no '`

**Comment by bengland2** [comment]
the last line of your post is interesting, perhaps there should be a parameter for which private key to use, And we should allow you to do StrictHostKeyChecking=no, though this should not be necessary as long as you have logged into the node once.    Thanks for reminding me of this.   If you want to submit a PR for this I'll take a look at it, otherwise I'll get around to fixing this when I get a chance.

But as for the exceptions, this means that the ssh threads did not see the "starting gun" (metaphor 100-yard dash) file in your --top directory's network_shared subdirectory, in this case /mnt/gluster/gv0_ganesha_nfs/smallfile/network_shared

Check that all your mountpoints were working.  Since you are using NFS, you may have to disable attribute caching, see [this section](https://github.com/bengland2/smallfile#use-with-distributed-filesystems) of documentation for details on how to test with NFS filesystems.

HTH

**Comment by bengland2** [comment]
Almost have fix checked in for this, turns out it was calculating timeouts incorrectly (before it knew the user's test configuration (threads, hosts).

**Comment by bengland2** [comment]
@g1patnaik fix is checked in, let me know if it is working for you.  You may need to adjust the --min-dirs-per-sec parameter to match what your filesystem can do, but you can now see the timeouts being computed if you use --output-json your-test.json,  see 'host-timeout' and 'startup-timeout'.

**Comment by bengland2** [comment]
I also added documentation about this [here](https://github.com/bengland2/smallfile/blob/master/README.md#the-dreaded-startup-timeout-error).

**Comment by g1patnaik** [comment]
Hi Ben,

Thanks. It's been a while I used this. I faced some troubles using this and
then switched to sysbench and fio and performed the parallel tests with
custom scripts. But I'll try to check this again.

Regards,
Jeevan.

**Comment by bengland2** [comment]
@g1patnaik, you have a day job, I get it ;-) I'm closing this but if you try it again etc , post it here and let me know thx.
