### ISSUE TITLE
Only working for localhost

### ISSUE THREAD

**Issue by agilmor** [bengland2/smallfile#8]
Hi,
I used smallfile a couple of years ago to get metric on a glusterfs setup using up to 4 hosts-set, and it worked great!

Now I'm kind of replicating my metrics with a cephfs, but I'm not able to do any test with any other host than the localhost?

I mean, lets use this  simple command:
```
./smallfile_cli.py --operation create --top $MY_MOUNTPOINT  --host-set $MY_HOSTNAME
```

Changing the calues of this command, I get this:
- if ```$MY_HOSTNAME``` is only the localhost, it works
- if ```$MY_HOSTNAME``` contains any other host (eg c7), it fails with:
```
Traceback (most recent call last):
  File "/imatge/imagen/smf-benchmark/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/imatge/imagen/smf-benchmark/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/imatge/imagen/smf-benchmark/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 7 seconds
ERROR: ssh thread for host c7 completed with status 256
  pickle file /mnt/cephfs/smf/network_shared/c7_result.pickle not found
no pickled invokes read, so no results
```
- Trying it with any ```$MY_MOUNTPOINT``` returns the same results
- No log files 

The ```ssh``` works fine without password on any host.
We're using Debian-Jessie ssh.

Do you have any idea that were the problem could be?

**Comment by bengland2** [comment]
@agilmor You must have passwordless ssh set up to all your hosts in --host-set parameter.  You must define a path to smallfile on the target systems, the default is to use the pathname on the initiator host (where you typed the command).  You must define the same shared mountpoint on all hosts, and the  --top parameter must point to a directory inside this shared mountpoint.    It works on localhost because these constraints don't matter then.  We've used it successfully on Cephfs and Glusterfs, smallfile doesn't care as long as the mountpoint behaves like a POSIX filesystem.  For troubleshooting, you can add parameter "--verbose Y".  The log files are in /var/tmp/invoke*log on the various host systems.    

Let me know if the documentation doesn't cover these points and I'll correct it.

**Comment by agilmor** [comment]
Hi!
Thanks for a so fast answer.
I think that we meet all the requeriments you mention

We've passwordless ssh:
```
$ ssh c1 hostname
c1
$ ssh c7 hostname
c7
```

The smallfile code is already in shared file system in the same directry in both nodes:
```
$ ssh c1 realpath smallfile_cli.py 
/imatge/imagen/smallfile_cli.py
$ ssh c7 realpath smallfile_cli.py 
/imatge/imagen/smallfile_cli.py
```

The --top parameter is also a shared directory in a shared mount point in both hosts (in this case just a NFS, but same results using other shared top directories):
```
$ ssh c1 df -h /imatge/imatge/smf-2018/
Filesystem                   Size  Used Avail Use% Mounted on
192.168.1.41:/export/imatge  3.0T  2.5T  398G  87% /imatge
$ ssh c7 df -h /imatge/imatge/smf-2018/
Filesystem                   Size  Used Avail Use% Mounted on
192.168.1.41:/export/imatge  3.0T  2.5T  398G  87% /imatge
```

When running it from c1 using c7 as host-set with verbose I get:

```
$ ./smallfile_cli.py --operation create --top /imatge/imatge/smf-2018/  --host-set c7 --verbose Y             
record size not specified, large files will default to record size 1024 KB
                                 version : 3.1
                           hosts in test : ['c7']
                   top test directory(s) : ['/imatge/imatge/smf-2018']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
             minimum directories per sec : 50
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : True
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /imatge/imagen/smf-benchmark/smallfile
               network thread sync. dir. : /imatge/imatge/smf-2018/network_shared
python /imatge/imagen/smf-benchmark/smallfile/smallfile_remote.py --network-sync-dir /imatge/imatge/smf-2018/network_shared  --as-host c7
shared dir list: ['param.pickle']
checking for host filename /imatge/imatge/smf-2018/network_shared/host_ready.c7.tmp
last_host_seen=-1 sec=0
shared dir list: ['param.pickle']
checking for host filename /imatge/imatge/smf-2018/network_shared/host_ready.c7.tmp
slave params: smf_test_params: version=3.1 json=None as_host=c7 host_set=['c7'] thread_count=2 remote_pgm_dir=/imatge/imagen/smf-benchmark/smallfileslave=True permute_host_dirs=False
 startup_timeout=2 host_timeout=7 smf_invoke= opname=create iterations=200 top_dirs=['/imatge/imatge/smf-2018'] src_dirs=['/imatge/imatge/smf-2018/file_srcdir'] dest_dirs=['/imatge/i
matge/smf-2018/file_dstdir'] network_dir=/imatge/imatge/smf-2018/network_shared shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on
_demand=False xattr_size=0 xattr_count=0 starting_gate=/imatge/imatge/smf-2018/network_shared/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_bet
ween_checks=20 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid= loglevel=20 filenum=0 filenum_final=0 rq=0 rq_final=0 start=None end=None elapsed=0 host=
c7 status=1 abort=False log_to_stderr=False verbose=True 
c7 saw /imatge/imatge/smf-2018/file_srcdir
c7 saw /imatge/imatge/smf-2018/file_dstdir
last_host_seen=-1 sec=2
shared dir list: ['host_ready.c7.tmp', 'param.pickle']
checking for host filename /imatge/imatge/smf-2018/network_shared/host_ready.c7.tmp
starting all threads by creating starting gate file /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
started 2 worker threads on host c7
threads not ready...
host c7 creating ready file /imatge/imatge/smf-2018/network_shared/host_ready.c7.tmp
awaiting /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
Traceback (most recent call last):
  File "/imatge/imagen/smf-benchmark/smallfile/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/imatge/imagen/smf-benchmark/smallfile/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/imatge/imagen/smf-benchmark/smallfile/multi_thread_workload.py", line 143, in run_multi_thread_workload
    % prm.host_startup_timeout)
Exception: starting signal not seen within 7 seconds
ERROR: ssh thread for host c7 completed with status 256
reading pickle file: /imatge/imatge/smf-2018/network_shared/c7_result.pickle
  pickle file /imatge/imatge/smf-2018/network_shared/c7_result.pickle not found
no pickled invokes read, so no results
```

In c7, the logs are quite empty (no logs on c1, where ths command was launched from):
```
$ cat /var/tmp/invoke_logs-00.log 
00 2018-03-07 16:15:53,273 - INFO - do_workload:  opname=create iterations=200 top_dirs=['/imatge/imatge/smf-2018'] src_dirs=['/imatge/imatge/smf-2018/file_srcdir/c7/thrd_00'] dest_dirs=['/imatge/imatge/smf-2018/file_dstdir/c7/thrd_00'] network_dir=/imatge/imatge/smf-2018/network_shared shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on_demand=False xattr_size=0 xattr_count=0 starting_gate=/imatge/imatge/smf-2018/network_shared/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_between_checks=20 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid=00 loglevel=20 filenum=0 filenum_final=0 rq=0 rq_final=0 start=None end=None elapsed=0 host=c7 status=1 abort=False log_to_stderr=False verbose=True
00 2018-03-07 16:15:53,274 - DEBUG - making all subdirs

$ cat /var/tmp/invoke_logs-01.log 
01 2018-03-07 16:15:53,274 - INFO - do_workload:  opname=create iterations=200 top_dirs=['/imatge/imatge/smf-2018'] src_dirs=['/imatge/imatge/smf-2018/file_srcdir/c7/thrd_01'] dest_dirs=['/imatge/imatge/smf-2018/file_dstdir/c7/thrd_01'] network_dir=/imatge/imatge/smf-2018/network_shared shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on_demand=False xattr_size=0 xattr_count=0 starting_gate=/imatge/imatge/smf-2018/network_shared/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_between_checks=20 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid=01 loglevel=20 filenum=0 filenum_final=0 rq=0 rq_final=0 start=None end=None elapsed=0 host=c7 status=1 abort=False log_to_stderr=False verbose=True
01 2018-03-07 16:15:53,274 - DEBUG - making all subdirs

$ cat /var/tmp/thread_ready.00.tmp 
$ cat /var/tmp/thread_ready.01.tmp 
```

We tried with ```--pause 1000``` but same results.

We have only some success changing code to increase the waiting time:
```
imatge@c1:~/smf-benchmark/smallfile>> git diff
diff --git a/smf_test_params.py b/smf_test_params.py
index 7a3a0d4..5b9981a 100644
--- a/smf_test_params.py
+++ b/smf_test_params.py
@@ -59,11 +59,11 @@ class smf_test_params:
         # assumes 100 directories/sec min creation rate
         # we have to create both src_dir and dst_dir trees so times 2
         # allow some time for thread synchronization
-        self.startup_timeout = 2 + (self.thread_count // 30) + ((dirs * 2) // self.min_directories_per_sec)
+        self.startup_timeout = 2 + (self.thread_count // 30) + ((dirs * 2) // self.min_directories_per_sec) + 100
         self.host_startup_timeout = self.startup_timeout
         if self.host_set is not None:
             # allow extra time for inter-host synchronization
-            self.host_startup_timeout += 5 + (len(self.host_set) // 2)
+            self.host_startup_timeout += 5 + (len(self.host_set) // 2) + 10
 
     def __str__(self):
         fmt = 'smf_test_params: version=%s json=%s as_host=%s host_set=%s '
```

In this later case, the logs:
```
01 2018-03-07 16:29:09,952 - DEBUG - making all subdirs
01 2018-03-07 16:29:39,546 - INFO - stonewalled after 200 iterations
01 2018-03-07 16:29:39,547 - DEBUG - exiting subprocess and returning invoke  opname=create iterations=200 top_dirs=['/imatge/imatge/smf-2018'] src_dirs=['/imatge/imatge/smf-2018/file_srcdir/c7/thrd_01'] dest_dirs=['/imatge/imatge/smf-2018/file_dstdir/c7/thrd_01'] network_dir=/imatge/imatge/smf-2018/network_shared shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on_demand=False xattr_size=0 xattr_count=0 starting_gate=/imatge/imatge/smf-2018/network_shared/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_between_checks=100 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid=01 loglevel=20 filenum=200 filenum_final=200 rq=200 rq_final=200 start=1520436549.96 end=1520436579.55 elapsed=29.5850839615 host=c7 status=0 abort=False log_to_stderr=False verbose=True
```

What do you think?
Could be the startup_timeout so related to ssh?
Are these 200 iteration for the stonewalled normal?

Thanks!

**Comment by agilmor** [comment]
Something is worng, but not sure what.
More info:


By the way, changing the ```startup_timeout``` removes the error and if only the remote host is used, everything works fine:
```
$ $PWD/smallfile/smallfile_cli.py --operation create --top /imatge/imatge/smf-2018/  --host-set c1

                                 version : 3.1
                           hosts in test : ['c1']
                   top test directory(s) : ['/imatge/imatge/smf-2018']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
             minimum directories per sec : 50
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /imatge/imagen/smf-benchmark/smallfile
               network thread sync. dir. : /imatge/imatge/smf-2018/network_shared
starting all threads by creating starting gate file /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
host = c1,thr = 00,elapsed = 29.634268,files = 200,records = 200,status = ok
host = c1,thr = 01,elapsed = 29.639972,files = 200,records = 200,status = ok
total threads = 2
total files = 400
total IOPS = 400
total data =     0.024 GiB
100.00% of requested files processed, minimum is  90.00
elapsed time =    29.640
files/sec = 13.495289
IOPS = 13.495289
MiB/sec = 0.843456
```

But I've notice that, running the same test but as a local node, the metrics are 10 times faster?
(note the initial ```ssh c1``` in the command)
```
$ ssh c1 -t $PWD/smallfile/smallfile_cli.py --operation create --top /imatge/imatge/smf-2018/  --host-set c1           
                                 version : 3.1
                           hosts in test : ['c1']
                   top test directory(s) : ['/imatge/imatge/smf-2018']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
             minimum directories per sec : 50
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /imatge/imatge/smf-benchmark/smallfile
               network thread sync. dir. : /imatge/imatge/smf-2018/network_shared
starting all threads by creating starting gate file /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
host = c1,thr = 00,elapsed = 3.488189,files = 200,records = 200,status = ok
host = c1,thr = 01,elapsed = 3.488272,files = 200,records = 200,status = ok
total threads = 2
total files = 400
total IOPS = 400
total data =     0.024 GiB
100.00% of requested files processed, minimum is  90.00
elapsed time =     3.488
files/sec = 114.669959
IOPS = 114.669959
MiB/sec = 7.166872
```

The mounted filesystem is just the same... so 10 times better/worse results has no sense?
It looks like the ssh threads are doing something wrong / different than non-ssh ones that procudes very bad results?

When using host-set with both, only the local are actually processed:
```
                                 version : 3.1
                           hosts in test : ['c1', 'c7']
                   top test directory(s) : ['/imatge/imatge/smf-2018']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
             minimum directories per sec : 50
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /imatge/imagen/smf-benchmark/smallfile
               network thread sync. dir. : /imatge/imatge/smf-2018/network_shared
starting all threads by creating starting gate file /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
host = c1,thr = 00,elapsed = 30.652462,files = 0,records = 0,status = ok
host = c1,thr = 01,elapsed = 30.652243,files = 0,records = 0,status = ok
host = c7,thr = 00,elapsed = 3.428237,files = 200,records = 200,status = ok
host = c7,thr = 01,elapsed = 3.426681,files = 200,records = 200,status = ok
total threads = 4
total files = 400
total IOPS = 400
total data =     0.024 GiB
 50.00% of requested files processed, minimum is  90.00
elapsed time =    30.652
files/sec = 13.049523
IOPS = 13.049523
MiB/sec = 0.815595
not enough total files processed, change test parameters
```

Note that if I run the same test from the other host, then the results are swaped (c1 is ok, c7 wrong):
```
$ ssh c1 -t $PWD/smallfile/smallfile_cli.py --operation create --top /imatge/imatge/smf-2018/  --host-set c1,c7
                                 version : 3.1
                           hosts in test : ['c1', 'c7']
                   top test directory(s) : ['/imatge/imatge/smf-2018']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
             minimum directories per sec : 50
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /imatge/imatge/smf-benchmark/smallfile
               network thread sync. dir. : /imatge/imatge/smf-2018/network_shared
starting all threads by creating starting gate file /imatge/imatge/smf-2018/network_shared/starting_gate.tmp
host = c1,thr = 00,elapsed = 3.492542,files = 200,records = 200,status = ok
host = c1,thr = 01,elapsed = 3.488894,files = 200,records = 200,status = ok
host = c7,thr = 00,elapsed = 30.647987,files = 0,records = 0,status = ok
host = c7,thr = 01,elapsed = 30.647463,files = 0,records = 0,status = ok
total threads = 4
total files = 400
total IOPS = 400
total data =     0.024 GiB
 50.00% of requested files processed, minimum is  90.00
elapsed time =    30.648
files/sec = 13.051428
IOPS = 13.051428
MiB/sec = 0.815714
not enough total files processed, change test parameters
Connection to c1 closed.
```

So, it is not an issue on the hosts, but an issue in the ssh commands somewhere?
It looks like the ssh commands are working with a so poor perfomance for some reason?
And probably, the reason that produces this poor perfomance on ssh commands in the same that triggers timeouts?

Please note that I'm using ths patch to avoid the inital issue (timeouts):
```
$ git diff
diff --git a/smf_test_params.py b/smf_test_params.py
index 7a3a0d4..d8256eb 100644
--- a/smf_test_params.py
+++ b/smf_test_params.py
@@ -59,11 +59,11 @@ class smf_test_params:
         # assumes 100 directories/sec min creation rate
         # we have to create both src_dir and dst_dir trees so times 2
         # allow some time for thread synchronization
-        self.startup_timeout = 2 + (self.thread_count // 30) + ((dirs * 2) // self.min_directories_per_sec)
+        self.startup_timeout = 2 + (self.thread_count // 30) + ((dirs * 2) // self.min_directories_per_sec) + 100
         self.host_startup_timeout = self.startup_timeout
         if self.host_set is not None:
             # allow extra time for inter-host synchronization
-            self.host_startup_timeout += 5 + (len(self.host_set) // 2)
+            self.host_startup_timeout += 5 + (len(self.host_set) // 2) + 100
 
     def __str__(self):
         fmt = 'smf_test_params: version=%s json=%s as_host=%s host_set=%s '
```

I use ssh so much between our network (even with frameworks like ROS) and we didn't detect any issue so far?

**Comment by bengland2** [comment]
@agilmor It's not ssh.  ssh is only used to start up the process that generates the workload on the remote node.

My suspicion is that it's something to do with NFS, specifically did you do NFS mount with option actimeo=1 like it says in the documentation?

mount -t nfs -o actimeo=1 your-linux-server:/your/nfs/export /mnt/nfs

The problem with NFS is that NFS clients that cache file attributes don't find out about attribute changes from the server for a long time, by default I think it's 30 sec.

**Comment by agilmor** [comment]
Hi!

You are right that I read about the ```actimeo``` and didn't use it... by bad.
But I've the exact same behaviour when the ```top``` is using a glusterfs mount point?

Anyway, I will try a NFS with the ```actimeo``` and will let you know!

Thanks!

**Comment by bengland2** [comment]
@agilmor, I'll assume this fixed it, closing, let me know if it didn't.
